name: Run Pre-commit Hooks with Postgres

on:
  pull_request:
    branches:
      [ "main", "feature/invest" ]
  push:
    branches:
      [ "main", "feature/invest" ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest



    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Run pre-commit hooks
      - name: Run pre-commit on all changed files
        run: |
          . venv/bin/activate

          # Определяем базовую ветку для сравнения
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            BASE_BRANCH="$GITHUB_BASE_REF"
          else
            BASE_BRANCH=$(echo "$GITHUB_REF" | sed 's/refs\/heads\///')
            BASE_BRANCH="origin/$BASE_BRANCH"
          fi

          # Получаем список измененных файлов
          files=$(git diff --name-only $BASE_BRANCH)

          # Если есть измененные файлы, запускаем pre-commit
          if [ -n "$files" ]; then
            pre-commit run --files $files
          else
            echo "No modified files to check."
          fi